package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// AppPermissionsable 
type AppPermissionsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetActions()(*AppPermissions_actions)
    GetAdministration()(*AppPermissions_administration)
    GetChecks()(*AppPermissions_checks)
    GetContents()(*AppPermissions_contents)
    GetDeployments()(*AppPermissions_deployments)
    GetEnvironments()(*AppPermissions_environments)
    GetIssues()(*AppPermissions_issues)
    GetMembers()(*AppPermissions_members)
    GetMetadata()(*AppPermissions_metadata)
    GetOrganizationAdministration()(*AppPermissions_organization_administration)
    GetOrganizationAnnouncementBanners()(*AppPermissions_organization_announcement_banners)
    GetOrganizationCustomRoles()(*AppPermissions_organization_custom_roles)
    GetOrganizationHooks()(*AppPermissions_organization_hooks)
    GetOrganizationPackages()(*AppPermissions_organization_packages)
    GetOrganizationPlan()(*AppPermissions_organization_plan)
    GetOrganizationProjects()(*AppPermissions_organization_projects)
    GetOrganizationSecrets()(*AppPermissions_organization_secrets)
    GetOrganizationSelfHostedRunners()(*AppPermissions_organization_self_hosted_runners)
    GetOrganizationUserBlocking()(*AppPermissions_organization_user_blocking)
    GetPackages()(*AppPermissions_packages)
    GetPages()(*AppPermissions_pages)
    GetPullRequests()(*AppPermissions_pull_requests)
    GetRepositoryAnnouncementBanners()(*AppPermissions_repository_announcement_banners)
    GetRepositoryHooks()(*AppPermissions_repository_hooks)
    GetRepositoryProjects()(*AppPermissions_repository_projects)
    GetSecrets()(*AppPermissions_secrets)
    GetSecretScanningAlerts()(*AppPermissions_secret_scanning_alerts)
    GetSecurityEvents()(*AppPermissions_security_events)
    GetSingleFile()(*AppPermissions_single_file)
    GetStatuses()(*AppPermissions_statuses)
    GetTeamDiscussions()(*AppPermissions_team_discussions)
    GetVulnerabilityAlerts()(*AppPermissions_vulnerability_alerts)
    GetWorkflows()(*AppPermissions_workflows)
    SetActions(value *AppPermissions_actions)()
    SetAdministration(value *AppPermissions_administration)()
    SetChecks(value *AppPermissions_checks)()
    SetContents(value *AppPermissions_contents)()
    SetDeployments(value *AppPermissions_deployments)()
    SetEnvironments(value *AppPermissions_environments)()
    SetIssues(value *AppPermissions_issues)()
    SetMembers(value *AppPermissions_members)()
    SetMetadata(value *AppPermissions_metadata)()
    SetOrganizationAdministration(value *AppPermissions_organization_administration)()
    SetOrganizationAnnouncementBanners(value *AppPermissions_organization_announcement_banners)()
    SetOrganizationCustomRoles(value *AppPermissions_organization_custom_roles)()
    SetOrganizationHooks(value *AppPermissions_organization_hooks)()
    SetOrganizationPackages(value *AppPermissions_organization_packages)()
    SetOrganizationPlan(value *AppPermissions_organization_plan)()
    SetOrganizationProjects(value *AppPermissions_organization_projects)()
    SetOrganizationSecrets(value *AppPermissions_organization_secrets)()
    SetOrganizationSelfHostedRunners(value *AppPermissions_organization_self_hosted_runners)()
    SetOrganizationUserBlocking(value *AppPermissions_organization_user_blocking)()
    SetPackages(value *AppPermissions_packages)()
    SetPages(value *AppPermissions_pages)()
    SetPullRequests(value *AppPermissions_pull_requests)()
    SetRepositoryAnnouncementBanners(value *AppPermissions_repository_announcement_banners)()
    SetRepositoryHooks(value *AppPermissions_repository_hooks)()
    SetRepositoryProjects(value *AppPermissions_repository_projects)()
    SetSecrets(value *AppPermissions_secrets)()
    SetSecretScanningAlerts(value *AppPermissions_secret_scanning_alerts)()
    SetSecurityEvents(value *AppPermissions_security_events)()
    SetSingleFile(value *AppPermissions_single_file)()
    SetStatuses(value *AppPermissions_statuses)()
    SetTeamDiscussions(value *AppPermissions_team_discussions)()
    SetVulnerabilityAlerts(value *AppPermissions_vulnerability_alerts)()
    SetWorkflows(value *AppPermissions_workflows)()
}
