package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// PagesHealthCheck_domainable 
type PagesHealthCheck_domainable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCaaError()(*string)
    GetDnsResolves()(*bool)
    GetEnforcesHttps()(*bool)
    GetHasCnameRecord()(*bool)
    GetHasMxRecordsPresent()(*bool)
    GetHost()(*string)
    GetHttpsError()(*string)
    GetIsApexDomain()(*bool)
    GetIsARecord()(*bool)
    GetIsCloudflareIp()(*bool)
    GetIsCnameToFastly()(*bool)
    GetIsCnameToGithubUserDomain()(*bool)
    GetIsCnameToPagesDotGithubDotCom()(*bool)
    GetIsFastlyIp()(*bool)
    GetIsHttpsEligible()(*bool)
    GetIsNonGithubPagesIpPresent()(*bool)
    GetIsOldIpAddress()(*bool)
    GetIsPagesDomain()(*bool)
    GetIsPointedToGithubPagesIp()(*bool)
    GetIsProxied()(*bool)
    GetIsServedByPages()(*bool)
    GetIsValid()(*bool)
    GetIsValidDomain()(*bool)
    GetNameservers()(*string)
    GetReason()(*string)
    GetRespondsToHttps()(*bool)
    GetShouldBeARecord()(*bool)
    GetUri()(*string)
    SetCaaError(value *string)()
    SetDnsResolves(value *bool)()
    SetEnforcesHttps(value *bool)()
    SetHasCnameRecord(value *bool)()
    SetHasMxRecordsPresent(value *bool)()
    SetHost(value *string)()
    SetHttpsError(value *string)()
    SetIsApexDomain(value *bool)()
    SetIsARecord(value *bool)()
    SetIsCloudflareIp(value *bool)()
    SetIsCnameToFastly(value *bool)()
    SetIsCnameToGithubUserDomain(value *bool)()
    SetIsCnameToPagesDotGithubDotCom(value *bool)()
    SetIsFastlyIp(value *bool)()
    SetIsHttpsEligible(value *bool)()
    SetIsNonGithubPagesIpPresent(value *bool)()
    SetIsOldIpAddress(value *bool)()
    SetIsPagesDomain(value *bool)()
    SetIsPointedToGithubPagesIp(value *bool)()
    SetIsProxied(value *bool)()
    SetIsServedByPages(value *bool)()
    SetIsValid(value *bool)()
    SetIsValidDomain(value *bool)()
    SetNameservers(value *string)()
    SetReason(value *string)()
    SetRespondsToHttps(value *bool)()
    SetShouldBeARecord(value *bool)()
    SetUri(value *string)()
}
