package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Rootable 
type Rootable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAuthorizationsUrl()(*string)
    GetCodeSearchUrl()(*string)
    GetCommitSearchUrl()(*string)
    GetCurrentUserAuthorizationsHtmlUrl()(*string)
    GetCurrentUserRepositoriesUrl()(*string)
    GetCurrentUserUrl()(*string)
    GetEmailsUrl()(*string)
    GetEmojisUrl()(*string)
    GetEventsUrl()(*string)
    GetFeedsUrl()(*string)
    GetFollowersUrl()(*string)
    GetFollowingUrl()(*string)
    GetGistsUrl()(*string)
    GetHubUrl()(*string)
    GetIssueSearchUrl()(*string)
    GetIssuesUrl()(*string)
    GetKeysUrl()(*string)
    GetLabelSearchUrl()(*string)
    GetNotificationsUrl()(*string)
    GetOrganizationRepositoriesUrl()(*string)
    GetOrganizationTeamsUrl()(*string)
    GetOrganizationUrl()(*string)
    GetPublicGistsUrl()(*string)
    GetRateLimitUrl()(*string)
    GetRepositorySearchUrl()(*string)
    GetRepositoryUrl()(*string)
    GetStarredGistsUrl()(*string)
    GetStarredUrl()(*string)
    GetTopicSearchUrl()(*string)
    GetUserOrganizationsUrl()(*string)
    GetUserRepositoriesUrl()(*string)
    GetUserSearchUrl()(*string)
    GetUserUrl()(*string)
    SetAuthorizationsUrl(value *string)()
    SetCodeSearchUrl(value *string)()
    SetCommitSearchUrl(value *string)()
    SetCurrentUserAuthorizationsHtmlUrl(value *string)()
    SetCurrentUserRepositoriesUrl(value *string)()
    SetCurrentUserUrl(value *string)()
    SetEmailsUrl(value *string)()
    SetEmojisUrl(value *string)()
    SetEventsUrl(value *string)()
    SetFeedsUrl(value *string)()
    SetFollowersUrl(value *string)()
    SetFollowingUrl(value *string)()
    SetGistsUrl(value *string)()
    SetHubUrl(value *string)()
    SetIssueSearchUrl(value *string)()
    SetIssuesUrl(value *string)()
    SetKeysUrl(value *string)()
    SetLabelSearchUrl(value *string)()
    SetNotificationsUrl(value *string)()
    SetOrganizationRepositoriesUrl(value *string)()
    SetOrganizationTeamsUrl(value *string)()
    SetOrganizationUrl(value *string)()
    SetPublicGistsUrl(value *string)()
    SetRateLimitUrl(value *string)()
    SetRepositorySearchUrl(value *string)()
    SetRepositoryUrl(value *string)()
    SetStarredGistsUrl(value *string)()
    SetStarredUrl(value *string)()
    SetTopicSearchUrl(value *string)()
    SetUserOrganizationsUrl(value *string)()
    SetUserRepositoriesUrl(value *string)()
    SetUserSearchUrl(value *string)()
    SetUserUrl(value *string)()
}
