package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// TeamOrganizationable 
type TeamOrganizationable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAvatarUrl()(*string)
    GetBillingEmail()(*string)
    GetBlog()(*string)
    GetCollaborators()(*int32)
    GetCompany()(*string)
    GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetDefaultRepositoryPermission()(*string)
    GetDescription()(*string)
    GetDiskUsage()(*int32)
    GetEmail()(*string)
    GetEventsUrl()(*string)
    GetFollowers()(*int32)
    GetFollowing()(*int32)
    GetHasOrganizationProjects()(*bool)
    GetHasRepositoryProjects()(*bool)
    GetHooksUrl()(*string)
    GetHtmlUrl()(*string)
    GetId()(*int32)
    GetIssuesUrl()(*string)
    GetIsVerified()(*bool)
    GetLocation()(*string)
    GetLogin()(*string)
    GetMembersAllowedRepositoryCreationType()(*string)
    GetMembersCanCreateInternalRepositories()(*bool)
    GetMembersCanCreatePages()(*bool)
    GetMembersCanCreatePrivatePages()(*bool)
    GetMembersCanCreatePrivateRepositories()(*bool)
    GetMembersCanCreatePublicPages()(*bool)
    GetMembersCanCreatePublicRepositories()(*bool)
    GetMembersCanCreateRepositories()(*bool)
    GetMembersCanForkPrivateRepositories()(*bool)
    GetMembersUrl()(*string)
    GetName()(*string)
    GetNodeId()(*string)
    GetOwnedPrivateRepos()(*int32)
    GetPlan()(TeamOrganization_planable)
    GetPrivateGists()(*int32)
    GetPublicGists()(*int32)
    GetPublicMembersUrl()(*string)
    GetPublicRepos()(*int32)
    GetReposUrl()(*string)
    GetTotalPrivateRepos()(*int32)
    GetTwitterUsername()(*string)
    GetTwoFactorRequirementEnabled()(*bool)
    GetType()(*string)
    GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetUrl()(*string)
    GetWebCommitSignoffRequired()(*bool)
    SetAvatarUrl(value *string)()
    SetBillingEmail(value *string)()
    SetBlog(value *string)()
    SetCollaborators(value *int32)()
    SetCompany(value *string)()
    SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetDefaultRepositoryPermission(value *string)()
    SetDescription(value *string)()
    SetDiskUsage(value *int32)()
    SetEmail(value *string)()
    SetEventsUrl(value *string)()
    SetFollowers(value *int32)()
    SetFollowing(value *int32)()
    SetHasOrganizationProjects(value *bool)()
    SetHasRepositoryProjects(value *bool)()
    SetHooksUrl(value *string)()
    SetHtmlUrl(value *string)()
    SetId(value *int32)()
    SetIssuesUrl(value *string)()
    SetIsVerified(value *bool)()
    SetLocation(value *string)()
    SetLogin(value *string)()
    SetMembersAllowedRepositoryCreationType(value *string)()
    SetMembersCanCreateInternalRepositories(value *bool)()
    SetMembersCanCreatePages(value *bool)()
    SetMembersCanCreatePrivatePages(value *bool)()
    SetMembersCanCreatePrivateRepositories(value *bool)()
    SetMembersCanCreatePublicPages(value *bool)()
    SetMembersCanCreatePublicRepositories(value *bool)()
    SetMembersCanCreateRepositories(value *bool)()
    SetMembersCanForkPrivateRepositories(value *bool)()
    SetMembersUrl(value *string)()
    SetName(value *string)()
    SetNodeId(value *string)()
    SetOwnedPrivateRepos(value *int32)()
    SetPlan(value TeamOrganization_planable)()
    SetPrivateGists(value *int32)()
    SetPublicGists(value *int32)()
    SetPublicMembersUrl(value *string)()
    SetPublicRepos(value *int32)()
    SetReposUrl(value *string)()
    SetTotalPrivateRepos(value *int32)()
    SetTwitterUsername(value *string)()
    SetTwoFactorRequirementEnabled(value *bool)()
    SetType(value *string)()
    SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetUrl(value *string)()
    SetWebCommitSignoffRequired(value *bool)()
}
