package orgs

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemWithOrgPatchRequestBodyable 
type ItemWithOrgPatchRequestBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAdvancedSecurityEnabledForNewRepositories()(*bool)
    GetBillingEmail()(*string)
    GetBlog()(*string)
    GetCompany()(*string)
    GetDependabotAlertsEnabledForNewRepositories()(*bool)
    GetDependabotSecurityUpdatesEnabledForNewRepositories()(*bool)
    GetDependencyGraphEnabledForNewRepositories()(*bool)
    GetDescription()(*string)
    GetEmail()(*string)
    GetHasOrganizationProjects()(*bool)
    GetHasRepositoryProjects()(*bool)
    GetLocation()(*string)
    GetMembersCanCreateInternalRepositories()(*bool)
    GetMembersCanCreatePages()(*bool)
    GetMembersCanCreatePrivatePages()(*bool)
    GetMembersCanCreatePrivateRepositories()(*bool)
    GetMembersCanCreatePublicPages()(*bool)
    GetMembersCanCreatePublicRepositories()(*bool)
    GetMembersCanCreateRepositories()(*bool)
    GetMembersCanForkPrivateRepositories()(*bool)
    GetName()(*string)
    GetSecretScanningEnabledForNewRepositories()(*bool)
    GetSecretScanningPushProtectionCustomLink()(*string)
    GetSecretScanningPushProtectionCustomLinkEnabled()(*bool)
    GetSecretScanningPushProtectionEnabledForNewRepositories()(*bool)
    GetTwitterUsername()(*string)
    GetWebCommitSignoffRequired()(*bool)
    SetAdvancedSecurityEnabledForNewRepositories(value *bool)()
    SetBillingEmail(value *string)()
    SetBlog(value *string)()
    SetCompany(value *string)()
    SetDependabotAlertsEnabledForNewRepositories(value *bool)()
    SetDependabotSecurityUpdatesEnabledForNewRepositories(value *bool)()
    SetDependencyGraphEnabledForNewRepositories(value *bool)()
    SetDescription(value *string)()
    SetEmail(value *string)()
    SetHasOrganizationProjects(value *bool)()
    SetHasRepositoryProjects(value *bool)()
    SetLocation(value *string)()
    SetMembersCanCreateInternalRepositories(value *bool)()
    SetMembersCanCreatePages(value *bool)()
    SetMembersCanCreatePrivatePages(value *bool)()
    SetMembersCanCreatePrivateRepositories(value *bool)()
    SetMembersCanCreatePublicPages(value *bool)()
    SetMembersCanCreatePublicRepositories(value *bool)()
    SetMembersCanCreateRepositories(value *bool)()
    SetMembersCanForkPrivateRepositories(value *bool)()
    SetName(value *string)()
    SetSecretScanningEnabledForNewRepositories(value *bool)()
    SetSecretScanningPushProtectionCustomLink(value *string)()
    SetSecretScanningPushProtectionCustomLinkEnabled(value *bool)()
    SetSecretScanningPushProtectionEnabledForNewRepositories(value *bool)()
    SetTwitterUsername(value *string)()
    SetWebCommitSignoffRequired(value *bool)()
}
